### ISSUE TITLE
GetHub FlowSteps for rjhaylor - Chittenengo, NY

### ISSUE THREAD

**Issue by rjhaylor** [githubteacher/everyone-may-2016#83]
## Task list

- [ ] Create a branch

- [ ] Add commits

- [ ] Open a pull request

- [ ] Conversation about PR 

- [ ] additional comments based on PR

- [ ] Merge branch
